export const INICIAL_IMAGES = [
  { src: 'assets/calzado_tennis1.jpg', alt: 'Calzado Tennis 1', title: 'Calzado Tennis 1' },
  { src: 'assets/calzado_tennis2.jpg', alt: 'Calzado Tennis 2', title: 'Calzado Tennis 2' },
  { src: 'assets/calzado_tennis3.jpg', alt: 'Calzado Tennis 3', title: 'Calzado Tennis 3' },
  { src: 'assets/calzado_TennisAdidas1.jpg', alt: 'Calzado Tennis Adidas 1', title: 'Calzado Tennis Adidas 1' },
  { src: 'assets/calzado_TennisDama1.jpg', alt: 'Calzado Tennis Dama 1', title: 'Calzado Tennis Dama 1' },
  { src: 'assets/calzado_TennisDama2.jpg', alt: 'Calzado Tennis Dama 2', title: 'Calzado Tennis Dama 2' },
  { src: 'assets/implementos_Balon_Baloncesto.jpg', alt: 'Implementos Balón Baloncesto', title: 'Implementos Balón Baloncesto' },
  { src: 'assets/implementos_Balon_Futbol.jpg', alt: 'Implementos Balón Fútbol', title: 'Implementos Balón Fútbol' },
  { src: 'assets/implementos_Pera_Boxeo.jpg', alt: 'Implementos Pera Boxeo', title: 'Implementos Pera Boxeo' },
  { src: 'assets/implementos_Saco_Boxeo.jpg', alt: 'Implementos Saco Boxeo', title: 'Implementos Saco Boxeo' },
  { src: 'assets/ropa_Buzo1.jpg', alt: 'Ropa Buzo 1', title: 'Ropa Buzo 1' },
  { src: 'assets/ropa_Buzo2.jpg', alt: 'Ropa Buzo 2', title: 'Ropa Buzo 2' },
  { src: 'assets/ropa_Pantaloneta1.jpg', alt: 'Ropa Pantaloneta 1', title: 'Ropa Pantaloneta 1' },
  { src: 'assets/ropa_ropaDeportiva.jpg', alt: 'Ropa Deportiva', title: 'Ropa Deportiva' },
  { src: 'assets/ropa_Sudadera1.jpg', alt: 'Ropa Sudadera 1', title: 'Ropa Sudadera 1' },
  { src: 'assets/suplementos_Aminoacidos.jpg', alt: 'Suplementos Aminoácidos', title: 'Suplementos Aminoácidos' },
  { src: 'assets/suplementos_Creatina.jpg', alt: 'Suplementos Creatina', title: 'Suplementos Creatina' },
  { src: 'assets/suplementos_Proteina_Whey.jpg', alt: 'Suplementos Proteína Whey', title: 'Suplementos Proteína Whey' },
  { src: 'assets/suplementos_Suplementos.jpg', alt: 'Suplementos', title: 'Suplementos' },
];
